# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0fd83d5407e4111b9329d4269d7f91fb9f6432add6580ecc167e5bfd0c2a5551378cb03984a00da88ac964c61fceb92f2f9bdc52cb1827cf334146eed3f5d071

test:
  secret_key_base: daa42b134d6eb508e1981759790ead825212c04c078955474cd4ceb1f71b188198590c53efd2cebe3c606a73ed6970c43dbefbec9d0f2ba8ab326b9735a0bf10

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
